'use client';

import { useEffect } from 'react';

export function ServiceWorkerRegistration() {
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      // Register main service worker (for caching - generated by next-pwa)
      navigator.serviceWorker
        .register('/service-worker.js')
        .then((registration) => {
          console.log('Main Service Worker registered:', registration.scope);
        })
        .catch((error) => {
          console.error('Main Service Worker registration failed:', error);
        });

      // Register push notification service worker
      navigator.serviceWorker
        .register('/push-sw.js')
        .then((registration) => {
          console.log('Push Service Worker registered:', registration.scope);
        })
        .catch((error) => {
          console.error('Push Service Worker registration failed:', error);
        });
    }
  }, []);

  return null;
}
